katalog/nginx/deployment.yml
katalog/nginx/kustomization.yaml

In order to leverage regex-based path matching we need to update nginx-ingress-controller to (at least) version 0.20.0.

Upgrade nginx-ingress-controller to 0.20.0

---

katalog/nginx/rbac.yml

Current fury-kubernetes-ingress release is missing networking.k8s.io
apiGroup in ingress-related resource in RBAC role. As a result this is
preventing the pods from starting up. This commit is adding the missing
apiGroup.
Together with this I've re-organized the list in order to put the
ingress-related resources close to each-other - as it's in the ingress
upstream:
https://github.com/kubernetes/ingress-nginx/blob/master/deploy/static/mandatory.yaml
The fix has been tested on a fresh GKE 1.14 cluster.

Add 'networking.k8s.io' apiGroup in ingress roles

---

README.md
katalog/dual-nginx/README.md
katalog/dual-nginx/deployment-external.yml
katalog/dual-nginx/deployment-internal.yml
katalog/nginx/README.md
katalog/nginx/deployment.yml

Hi team.
Actually, we are providing nginx-ingress-controller version 0.25.1. 
Seems like the sticky session feature is partially-broken and it is fixed in version 0.26.0: [**Merged PR**](https://github.com/kubernetes/ingress-nginx/pull/4478). 
As it is a newer version that applies a hotfix to 0.26.0 version, I suggest to update our package to provide `nginx-ingress-controller` version **0.26.1** (actual latest)
Thanks!

Update nginx ingress controller version

---

README.md
katalog/forecastle/deploy.yml
katalog/tests/tests.bats

The aim of this PR is to update forecastle to v1.0.34, this way we can use the `forecastle.stakater.com/url` to overwrite the URL inferred from the ingress to allow, for example, for non-standard ports.
I left out the new CRD on purpose as I don't think it could be of any use to us.

Update forecastle to v1.0.34

---

katalog/cert-manager/README.md

The following PR just include a few documented step to be followed in order to deploy certmanager, depending on the nginx flavour you've selected (single or dual-nginx). 
This is just the first step, that further need to be ported also to the ufficial docs as well.
Let me know!

Added documented step for deploy certManager accordingly with nginx flavour

---

README.md
katalog/dual-nginx/README.md
katalog/nginx/README.md
katalog/nginx/bases/controller/deployment.yml
katalog/nginx/bases/controller/kustomization.yaml

The aim of this PR is to update ingress-nginx to 0.30.0
Summary of changes:
- updated ingress-nginx to 0.30.0
- updated ingress-nginx UID due to changes in the upstream project
No particular care has to be taken to update from Fury's current version (0.26.1) to 0.30.0.

Update ingress-nginx to 0.30.0

---

katalog/forecastle/README.md
katalog/forecastle/config.yaml
katalog/forecastle/deploy.yml
katalog/forecastle/kustomization.yaml
katalog/forecastle/rbac.yml

The aim of this PR is to update Forecastle to v1.0.42.
Summary of changes:
- updated Forecastle to v1.0.42
- added `securityContext` to Forecastle container
- added README
No particular care has to be taken to update from Fury's current version (v1.0.34) to v1.0.42.
Please note that I've disabled Forecastle CRD support (see [here](https://github.com/stakater/Forecastle#forecastleapp-crd)) since it seemed a little overkill to me.

Update Forecastle to v1.0.42

---

docs/releases/unreleased.md
katalog/cert-manager/dashboards/cert-manager.json
katalog/cert-manager/dashboards/kustomization.yaml
katalog/cert-manager/kustomization.yaml

Hi team!
This pr adds a new dashboard to Grafana. This time to monitor certificates issued by cert-manager
It has this: https://grafana.com/grafana/dashboards/11001 base but i modified a couple of queries to make it working properly.
Thanks

Add cert-manager dashboard

---

docs/releases/unreleased.md
katalog/dual-nginx/patch/rbac.yml
katalog/nginx/bases/configs/rbac.yml

Without these permissions, the dual nginx ingress is unable to elect a leader.
Hence, the ingress is not able to set the address on ingresses (and it generates more errors in cascade).
Reference for the fix: https://github.com/kubernetes/ingress-nginx/issues/1976#issuecomment-469020715

Fix: add missing permissions

---

.bumpversion.cfg
.drone.yml
README.md
docs/releases/v1.9.0.md
examples/nginx-config/Furyfile.yml
examples/nginx-default-ssl-certificate/Furyfile.yml
examples/nginx-ldap-auth/Furyfile.yml
katalog/cert-manager/README.md
katalog/cert-manager/cainjector/kustomization.yaml
katalog/cert-manager/cert-manager-controller/kustomization.yaml
katalog/cert-manager/kustomization.yaml
katalog/cert-manager/retrocompatible-version-label.yaml
katalog/cert-manager/version-label.yaml
katalog/cert-manager/webhook/kustomization.yaml
katalog/dual-nginx/README.md
katalog/forecastle/README.md
katalog/forecastle/kustomization.yaml
katalog/nginx-gke/README.md
katalog/nginx-ldap-auth/kustomization.yaml
katalog/nginx-ldap-auth/nginx-ldap-auth.yaml
katalog/nginx-ovh/README.md
katalog/nginx/README.md
katalog/nginx/bases/controller/deployment.yml
katalog/nginx/bases/controller/global-labels.yaml
katalog/nginx/bases/controller/kustomization.yaml
katalog/tests/nginx-ldap-auth.sh
katalog/tests/nginx-ldap-auth/httpbin.yaml
katalog/tests/nginx-ldap-auth/ldap-registry.yaml
katalog/tests/nginx-ldap-auth/ldap-server.yaml
katalog/tests/tests.bats

Ciao Team!
As you probable know, I'm starting to craft a new Fury release. It includes:
- Upgrade [cert-manager](../../katalog/cert-manager). From v1.0.1 to
[v1.1.0](https://github.com/jetstack/cert-manager/releases/tag/v1.1.0)
- Upgrade [nginx-ingress-controller](../../katalog/nginx) and its variants
(from v0.35.0 to [v0.42.0](https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v0.42.0)):
- [dual-nginx](../../katalog/dual-nginx)
- [nginx-gke](../../katalog/nginx-gke)
- [nginx-ovh](../../katalog/nginx-ovh)
- Upgrade [forecastle](../../katalog/forecastle). From 1.0.57 to
[1.0.61](https://github.com/stakater/Forecastle/releases/tag/v1.0.61)
- Kubernetes support:
- Deprecate Kubernetes 1.16 support.
- Kubernetes 1.19 is considered stable.
- Add tech-preview support to …

Release 1.9.0

---

.drone.yml
README.md
katalog/pomerium/README.md
katalog/pomerium/config/config.example.env
katalog/pomerium/config/policy.example.yaml
katalog/pomerium/deploy.yml
katalog/pomerium/ingress.yml
katalog/pomerium/kustomization.yaml
katalog/pomerium/kustomize-config.yml
katalog/pomerium/namespace.yml
katalog/pomerium/secrets/pomerium.example.env
katalog/pomerium/svc.yml

Hi everyone 👋 ,
with the special guest of @nikever  and @nutellinoit, I implemented the addition of pomerium as an authentication proxy behind services, in order to standardize the authentication method for services deployed in the cluster.
I am proposing the kustomize receipt, probably is missing something or can be better somehow.
I ask you to give it a look and suggest whatever you think to enhance it 👍

adding Pomerium as zero-trust proxy service

---

katalog/dual-nginx/README.md
katalog/nginx-gke/README.md
katalog/nginx-ovh/README.md
katalog/nginx/README.md

This PR adds a warning on the deployment instructions for NGINX Ingress Controller about the NodeSelector that should be added to the default DaemonSet.

Add Nodeselector instructions to NGINX Readme

---

katalog/cert-manager/cainjector/deploy.yml
katalog/cert-manager/cert-manager-controller/deploy.yml
katalog/cert-manager/cert-manager-controller/sm.yml
katalog/cert-manager/kustomization.yaml
katalog/cert-manager/webhook/deploy.yml

stop using app=cert-manager as unique label for all deployments and start using the same labels as upstream.
fixes #90
BREAKING: changes to immutable fields. You need to delete cert-manager, cert-manager-webhook and cert-manager-cainjector deployments before applying.

fix(cert-manager)!: align labels with upstream

---

katalog/cert-manager/MAINTENANCE.md
katalog/cert-manager/cainjector/rbac.yml
katalog/cert-manager/cert-manager-controller/rbac.yml

Add RBAC permissions for get configmaps so the leader election can work in the cert-manager namespace.
Upstream doesn't need this permissions because they use `kube-system` namespace for leader election.
fixes #91

fix(cert-manager): missing permission for leader-election

---

.gitignore
katalog/forecastle/README.md
katalog/forecastle/config.yaml
katalog/forecastle/crd.yml
katalog/forecastle/deploy.yml
katalog/forecastle/kustomization.yaml

fixes #99
* **forecastle:** enable crds for the controller ([45cf498](https://github.com/sighupio/fury-kubernetes-ingress/commit/45cf498f3cae5ad6f21adc6d5b1b3bb7d9125bac))
* **forecastle:** update to version v1.0.119 and add crd ([3cfbb62](https://github.com/sighupio/fury-kubernetes-ingress/commit/3cfbb623ec233cda7a3538550e836fbad8d10dcc))
add the possibility of adding elements to the forecastle catalog using CustomResources was enabled, for this it was necessary to add the CustomResourceDefinition and allow this possibility in the controller configuration. 
soruce: https://github.com/stakater/Forecastle

feat(forecastle): update to version v1.0.119 and add crd

---

katalog/cert-manager/dashboards/kustomization.yaml
katalog/nginx/bases/configs/dashboards/kustomization.yaml

Add annotation to put the module's Grafana dashboards inside the "Ingress" folder for better organization.

feat: put dashboards in "Ingress" grafana folder

---

README.md
katalog/external-dns/MAINTENANCE.md
katalog/external-dns/base/deploy.yml

commit message:
Updated External DNS Image: Enhanced EKS support & added `eu-central-2` region
- Updated the external DNS image version which now works well in EKS environments. Local testing wasn't possible but cloud testing was successful.
- Added support for the `eu-central-2` region.
- Created a basic guide for project maintenance, see `MAINTENANCE.md` for details.
Please test this update in your local environment and provide feedback.

feat(external-dns): update image and add maintenance guide

---

README.md
katalog/cert-manager/MAINTENANCE.md
katalog/cert-manager/README.md
katalog/cert-manager/cainjector/deploy.yml
katalog/cert-manager/cert-manager-controller/crd.yml
katalog/cert-manager/cert-manager-controller/deploy.yml
katalog/cert-manager/cert-manager-controller/kustomization.yaml
katalog/cert-manager/webhook/deploy.yml

This PR updates the cert-manager and addresses the concerns raised in Issue #119. The issue was resolved by adding a patch to the kustomization file located at `katalog/cert-manager/cert-manager-controller/kustomization.yaml`. The patch ensures that the `--acme-http01-solver-image` argument now points to an image hosted on the SIGHUP container registry, as shown below:
```yaml
patchesJson6902:
- target:
group: apps
version: v1
kind: Deployment
name: cert-manager
patch: |-
- op: replace
path: /spec/template/spec/containers/0/args/6
value: --acme-http01-solver-image=registry.sighup.io/fury/cert-manager-acmesolver:v1.14.2
```
Additionally, the maintenance guide has been updated, and the manifests have been thoroughly reviewed. We've incorporated missing liveness probes found in the upstream …

Update Cert-Manager v 1.14.2 and Resolve Issue #119

---

README.md
katalog/forecastle/README.md
katalog/forecastle/deploy.yml

This PR update Forecastle to de version 1.0.136, was testing on a Kubernetes cluster  created using kind, the key points from the QA, and testing phase include:
- Deploy the workload in Kubernetes version 1.28.6 and 1.29.1
- validate forecastle's CRD functionally by successfully creating a CR and ings, which were both published in the services directory.

Feature/forecastle version bump 1.0.136

---

README.md
katalog/external-dns/README.md
katalog/external-dns/base/deploy.yml
katalog/external-dns/base/rbac.yml
katalog/external-dns/private/kustomization.yaml
katalog/external-dns/public/kustomization.yaml

This PR updates `external-dns` to the version `v0.14.0` and was  testing on Kubernetes clusters. The manifests format was update using the correct indentantion. 
Key points from the QA and testing phase include:
- Tested on Kubernetes clusters using kind versions 1.29.1 and 1.28.6.
- Confirmed all workloads were operational across clusters.
- Validated the `external-dns` its capable to create, update and delete records using cloudflare provider.

feat(external-dns): version bump v0.14.0 and formating

---

README.md
katalog/dual-nginx/README.md
katalog/nginx/README.md
katalog/nginx/bases/controller/kustomization.yaml

This PR updates nginx to version v1.9.6 and was tested on Kubernetes clusters. 
Key points from the QA and testing phase include:
- Tested on Kubernetes clusters using kind versions 1.29.1 and 1.28.6.
- Confirmed all workloads were operational across clusters.
- Dual nginx implementation was tested with two ingress resources (internal and external) using a valid DNS record and NodePort services.

Nginx version bump v1.9.6

---

katalog/nginx/bases/configs/rules.yml

Hi 👋 
This PR is to fix the queries that generate certificate expiration alerts.
As of today, we just compute the value of nginx_ingress_controller_ssl_expire_time_seconds, but this is actually the epoch timestamp of the expiration date.
To measure how much time remains till the expiration, we need to subtract the current time, that is `time()`.

Fix Nginx Prometheus Rules

---

README.md
katalog/external-dns/README.md
katalog/external-dns/base/deploy.yml
katalog/external-dns/base/kustomization.yaml

Updated the external-dns image tag to v0.15.0 and moved tag handling on `kustomization.yaml`

Feat/sighupio/product management#441/update external dns

---

README.md
katalog/forecastle/README.md
katalog/forecastle/deploy.yml

- Updated forecastle image tag to `v1.0.145`
- docs: updated version in forecastle module

Feat/sighupio/product management#442/update forecastle

---

.drone.yml

Changes:
- updated `pluto` target version to 1.31
- removed e2e test for version 1.26.6 and 1.27.3
- updated `kind` to 0.24
- updated `sighup/e2e-testing` image using the new one with bats, kubectl, customize and  yq
- add e2e test for version 1.30.5 and 1.31.1
Depends on:

ci(e2e-test): add test for k8s 1.30.5 and 1.31.1

---

.drone.yml

- Drop CI e2e tests for Kubernetes 1.28
- Add CI e2e tests for Kubernetes 1.32.2
- Bump API version compatibility check to 1.32
- Switch to kustomize 5.6.0 for e2e
Closes https://github.com/sighupio/product-management/issues/576
See above
None
NA
NA

chore(ci): drop 1.28, add 1.32, kustomize 5.6.0

---

docs/releases/unreleased.md
katalog/cert-manager/MAINTENANCE.md
katalog/cert-manager/README.md
katalog/cert-manager/cainjector/deploy.yml
katalog/cert-manager/cert-manager-controller/crd.yml
katalog/cert-manager/cert-manager-controller/deploy.yml
katalog/cert-manager/cert-manager-controller/kustomization.yaml
katalog/cert-manager/cert-manager-controller/rbac.yml
katalog/cert-manager/webhook/deploy.yml

- Bump cert-manager to v1.17.1
- Move customizations applied directly to the manifests to Kustomize patches for better maintainability
- Update docs
- Updated kustomize projects to use v5-compatible features.
- New images have already been synced to SIGHUP's registry.
Fixes https://github.com/sighupio/product-management/issues/572
> [!NOTE]
> This PR is based on #143. You will see changes introduced by both PRs until 143 gets merged.
See summary.
None
I feel like the maintenance of this package could be more automated. It may be worthy to spend some time to create some scripts.
Also, there's a mix of usage of the `kube-system` and `cert-manager` namespaces that creates some confusion and the docs may be outdated regarding that.

feat(cert-manager): upgrade to v1.17.1

---

README.md
docs/COMPATIBILITY_MATRIX.md
docs/releases/v4.0.0.md
katalog/cert-manager/README.md
katalog/dual-nginx/README.md
katalog/nginx/README.md

Update docs for releasing v4.0.0
closes https://github.com/sighupio/product-management/issues/577
Documentation for releasing v4.0.0 of the module, I decided to bump a major being that are user-facing breaking changes introduced.
The breaking changes don't change the deployment mode nor need extra care, there are some features that have been dropped by upstream that we are not directly using but our users could be.
Non by this PR.
N.A.
N.A.

feat: prepare for releasing v4.0.0

---

README.md
docs/releases/v4.0.0.md
katalog/dual-nginx/README.md
katalog/nginx/README.md
katalog/nginx/bases/configs/ClusterRole-ingress-nginx.yml
katalog/nginx/bases/configs/ClusterRoleBinding-ingress-nginx.yml
katalog/nginx/bases/configs/PrometheusRule-ingress-nginx-controller.yml
katalog/nginx/bases/configs/Role-ingress-nginx.yml
katalog/nginx/bases/configs/RoleBinding-ingress-nginx.yml
katalog/nginx/bases/configs/Service-ingress-nginx-controller-metrics.yml
katalog/nginx/bases/configs/ServiceAccount-ingress-nginx.yml
katalog/nginx/bases/configs/ServiceMonitor-ingress-nginx-controller.yml
katalog/nginx/bases/controller/ConfigMap-ingress-nginx-controller.yml
katalog/nginx/bases/controller/DaemonSet-ingress-nginx-controller.yml
katalog/nginx/bases/controller/IngressClass-nginx.yml
katalog/nginx/bases/controller/Service-ingress-nginx-controller-admission.yml
katalog/nginx/bases/controller/Service-ingress-nginx-controller.yml
katalog/nginx/bases/controller/ValidatingWebhookConfiguration-ingress-nginx-admission.yml
katalog/nginx/bases/controller/kustomization.yaml

This PR updates the Nginx Ingress Controller version to v1.12.1 to correct and fix a critical 9.8 vulnerability.
Relates to [this](https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v1.12.1).
None reported.
None.

chore: update nginx ingress controller to 1.12.1

---

katalog/forecastle/config.yaml

Update Forecastle branding to SIGHUP Distribution:
See above
Only my heart </3 RIP Fury
See screenshot above
Hopefully none

fix(forecastle): Use SIGHUP Distribution branding

---

.github/pull_request_template.md
katalog/dual-nginx/external/patch/validating-webhook.yml
katalog/dual-nginx/internal/patch/validating-webhook.yml

I found two mistyped `value` in the `validating-webhook.yml` patch for internal and external `ValidatingWebhookConfiguration`.
Self-explanatory
None
None
None

fix(dual-nginx): Fix typo in validating-webhook patch for internal and external

---

README.md
docs/COMPATIBILITY_MATRIX.md
docs/releases/v4.1.1.md
examples/nginx-config/Furyfile.yml
examples/nginx-default-ssl-certificate/Furyfile.yml
examples/nginx-gke/README.md
examples/nginx-ovh/README.md
katalog/dual-nginx/README.md
katalog/nginx/MAINTENANCE.md
katalog/nginx/MAINTENANCE.values.yml
katalog/nginx/README.md
katalog/nginx/bases/configs/ClusterRole-ingress-nginx.yml
katalog/nginx/bases/configs/ClusterRoleBinding-ingress-nginx.yml
katalog/nginx/bases/configs/PrometheusRule-ingress-nginx-controller.yml
katalog/nginx/bases/configs/Role-ingress-nginx.yml
katalog/nginx/bases/configs/RoleBinding-ingress-nginx.yml
katalog/nginx/bases/configs/Service-ingress-nginx-controller-metrics.yml
katalog/nginx/bases/configs/ServiceAccount-ingress-nginx.yml
katalog/nginx/bases/configs/ServiceMonitor-ingress-nginx-controller.yml
katalog/nginx/bases/controller/ConfigMap-ingress-nginx-controller.yml
katalog/nginx/bases/controller/DaemonSet-ingress-nginx-controller.yml
katalog/nginx/bases/controller/IngressClass-nginx.yml
katalog/nginx/bases/controller/Service-ingress-nginx-controller-admission.yml
katalog/nginx/bases/controller/Service-ingress-nginx-controller.yml
katalog/nginx/bases/controller/ValidatingWebhookConfiguration-ingress-nginx-admission.yml
katalog/nginx/bases/controller/kustomization.yaml
katalog/nginx/upgrade.sh

Upgrade ingress-nginx controller from v1.13.1 to v1.13.3 (chart 4.13.3) to fix pod startup failures caused by a hard-coded `proxy_busy_buffers_size` default that conflicted with NGINX's validation when custom proxy buffer configurations were used.
Changes:
- Updated controller image tag from `v1.13.1` to `v1.13.3`
- Updated Helm chart version from `4.13.0` to `4.13.3`
- Updated `MAINTENANCE.md` and `MAINTENANCE.values.yml`
- Updated `README.md` with v1.13.3 versions
- Updated release notes
- Updated `docs/COMPATIBILITY_MATRIX.md`
None.
None.

feat(nginx): upgrade ingress-nginx-controller to v1.13.3
